export default {
	SHOW_COUNTRY: 'SHOW_COUNTRY',
	REQUEST_COUNTRY: 'REQUEST_COUNTRY',
	RECEIVE_COUNTRY: 'RECEIVE_COUNTRY',
	RECEIVE_COUNTRY_FAILURE: 'RECEIVE_COUNTRY_FAILURE',
	HIDE_COUNTRY: 'HIDE_COUNTRY'
};
